# Generated by Django 5.2 on 2025-04-03 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialgoal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
        migrations.AlterField(
            model_name='financialgoal',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
