# Generated by Django 5.2 on 2025-04-03 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250404_0312'),
        ('core', '0003_financialgoal_category_alter_financialgoal_name'),
    ]

    operations = [
    ]
