# Generated by Django 5.2 on 2025-04-04 03:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20250404_0318'),
    ]

    operations = [
        # Add created_at to Category if missing
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        # Add updated_at to Category if missing
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Add created_at to Transaction if missing
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        # Add updated_at to Transaction if missing
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Add updated_at to FinancialGoal if missing
        migrations.AddField(
            model_name='financialgoal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
